version: "3.9"

services:
    nebula-db:
        image: postgres:14-alpine
        ports:
            - "5432:5432"

        environment:
            - POSTGRES_PASSWORD=nebulapi
            - POSTGRES_USER=nebulapi
            - POSTGRES_DB=nebulapi

        volumes:
            - ./dbdata:/var/lib/postgresql/data/

    nebula-django:
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - ./.env
        environment:
            - POSTGRES_PASSWORD=nebulapi
            - POSTGRES_USER=nebulapi
            - POSTGRES_DB=nebulapi

        ports:
            - "8000:8000"

        volumes:
            - ./src:/app/src

        depends_on:
            - nebula-db
