# Generated by Django 4.2.2 on 2023-06-27 07:56

import datetime

import django.db.models.deletion
from django.db import migrations, models

import core_api.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                ("id", models.SlugField(primary_key=True, serialize=False)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            (
                                core_api.models.NewsSource["mind"],
                                "Microsoft News Dataset",
                            )
                        ],
                        default=core_api.models.NewsSource["mind"],
                    ),
                ),
                ("category", models.CharField(max_length=20)),
                ("subcategory", models.CharField(max_length=30)),
                ("title", models.TextField()),
                ("abstract", models.TextField()),
                ("url", models.URLField()),
                (
                    "publishing_date",
                    models.DateTimeField(default=datetime.datetime.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NewsImpression",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core_api.newsarticle",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="management.user",
                    ),
                ),
            ],
        ),
    ]
