# Generated by Django 4.2.2 on 2023-06-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsarticle",
            name="subcategory",
            field=models.CharField(max_length=40),
        ),
    ]
